# Generated by Django 5.2.13 on 2026-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='رقم الأتوبيس - مثلاً: BUS-01', max_length=20, unique=True)),
                ('plate_number', models.CharField(help_text='رقم اللوحة', max_length=20, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=40, help_text='عدد المقاعد')),
                ('status', models.CharField(choices=[('active', 'شغال'), ('inactive', 'مش شغال'), ('maintenance', 'صيانة'), ('en_route', 'في الطريق'), ('arrived', 'وصل')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='خط العرض', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='خط الطول', max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, help_text='السرعة بالكيلومتر/ساعة', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='الاتجاه بالدرجات', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bus Location',
                'verbose_name_plural': 'Bus Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الخط - مثلاً: كفر الشيخ - الجامعة', max_length=100)),
                ('description', models.TextField(blank=True, help_text='وصف الخط', null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم المحطة', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveSmallIntegerField(help_text='ترتيب المحطة')),
                ('estimated_arrival_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['order'],
            },
        ),
    ]
