# Generated by Django 5.2.13 on 2026-04-18 01:35

import apps.students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='صورة الوجه', upload_to=apps.students.models.face_image_upload_path)),
                ('label', models.CharField(blank=True, help_text='وصف الصورة (أمام، يمين، شمال)', max_length=50, null=True)),
                ('face_embedding', models.TextField(blank=True, help_text='الـ face vector - بيتملا أوتوماتيك', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='هل تم معالجة الصورة واستخراج الـ embedding؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Face Image',
                'verbose_name_plural': 'Face Images',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(help_text='الرقم الجامعي', max_length=20, unique=True)),
                ('faculty', models.CharField(help_text='الكلية', max_length=100)),
                ('department', models.CharField(help_text='القسم', max_length=100)),
                ('academic_year', models.PositiveSmallIntegerField(help_text='السنة الدراسية (1-5)')),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='خط العرض', max_digits=9, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='خط الطول', max_digits=9, null=True)),
                ('home_address', models.TextField(blank=True, help_text='العنوان كنص (اختياري)', null=True)),
                ('assigned_bus', models.CharField(blank=True, help_text='رقم الأتوبيس المخصص', max_length=20, null=True)),
                ('is_face_registered', models.BooleanField(default=False, help_text='هل تم تسجيل الوجه؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
