# Generated by Django 5.2.14 on 2026-06-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=500, null=True),
        ),
    ]
