# Generated by Django 5.2.13 on 2026-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('boarding', 'ركب الأتوبيس'), ('leaving', 'نزل من الأتوبيس')], default='boarding', max_length=10)),
                ('recognition_status', models.CharField(choices=[('recognized', 'تم التعرف'), ('unrecognized', 'لم يتم التعرف'), ('error', 'خطأ في المعالجة')], default='unrecognized', max_length=15)),
                ('confidence_score', models.FloatField(blank=True, help_text='نسبة الثقة في التعرف (0.0 - 1.0)', null=True)),
                ('captured_image', models.ImageField(blank=True, help_text='الصورة الملتقطة من الكاميرا', null=True, upload_to='attendance/captures/')),
                ('bus_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bus_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر')], default='absent', max_length=10)),
                ('boarding_time', models.DateTimeField(blank=True, null=True)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendance',
                'ordering': ['-date'],
            },
        ),
    ]
