# Generated by Django 5.2.14 on 2026-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='boarding_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط عرض موقع الصعود', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='boarding_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط طول موقع الصعود', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='leaving_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط عرض موقع النزول', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='leaving_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط طول موقع النزول', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='boarding_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط عرض موقع الصعود', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='boarding_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط طول موقع الصعود', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='leaving_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط عرض موقع النزول', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='leaving_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='خط طول موقع النزول', max_digits=9, null=True),
        ),
    ]
